// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1HQjP8D7e9Ey0Lv4N1bDIbJLlyrxYtn4',
    appId: '1:901311202194:web:2858daeb9be11ffdf4774b',
    messagingSenderId: '901311202194',
    projectId: 'mybike-865b8',
    authDomain: 'mybike-865b8.firebaseapp.com',
    storageBucket: 'mybike-865b8.firebasestorage.app',
    measurementId: 'G-M3DM5ZL9KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8rHmDOCo6H4mnKDMJO6FvOr9fIXn5LA',
    appId: '1:901311202194:android:786b6005c405ca65f4774b',
    messagingSenderId: '901311202194',
    projectId: 'mybike-865b8',
    storageBucket: 'mybike-865b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCek-dzyguX4Ra-8lQT9XVi69aYUtHoI-U',
    appId: '1:901311202194:ios:9878ed9c95660ed1f4774b',
    messagingSenderId: '901311202194',
    projectId: 'mybike-865b8',
    storageBucket: 'mybike-865b8.firebasestorage.app',
    iosClientId: '901311202194-gm2iud3fcqb9qtlaf3b550kbbrrshse3.apps.googleusercontent.com',
    iosBundleId: 'com.mybike.mybike',
  );
}
